name: SentioFakePlayer
version: 1.0.0
main: com.sentio.fakeplayer.SentioFakePlayer
api-version: '1.21'

author: Sentio
description: Fake Player system for Sentio Network


commands:

  fakeplayer:
    description: Manage fake players
    usage: /fakeplayer <create|remove|list>
    aliases:
      - fp



permissions:

  sentio.fakeplayer:
    description: Use FakePlayer commands
    default: op
